import jsPDF from 'jspdf';

export const exportReportPDF = (report: any, userName: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header background
  doc.setFillColor(15, 15, 24);
  doc.rect(0, 0, pageWidth, 40, 'F');

  // Title
  doc.setTextColor(79, 142, 247);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('MediScan AI', 14, 18);

  doc.setTextColor(160, 174, 192);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('AI-Powered Blood Report Analysis', 14, 27);

  // Date and patient
  doc.setTextColor(160, 174, 192);
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 14, 18, { align: 'right' });
  doc.text(`Patient: ${userName}`, pageWidth - 14, 27, { align: 'right' });

  y = 55;

  // Section title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Blood Test Results', 14, y);
  y += 10;

  // Divider
  doc.setDrawColor(79, 142, 247);
  doc.setLineWidth(0.5);
  doc.line(14, y, pageWidth - 14, y);
  y += 10;

  // Tests table header
  doc.setFillColor(240, 244, 255);
  doc.rect(14, y - 5, pageWidth - 28, 10, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(50, 50, 50);
  doc.text('Test Name', 16, y + 1);
  doc.text('Value', 90, y + 1);
  doc.text('Normal Range', 120, y + 1);
  doc.text('Status', 170, y + 1);
  y += 12;

  // Tests rows
  if (report.tests) {
    report.tests.forEach((test: any, index: number) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      // Alternating row background
      if (index % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(14, y - 5, pageWidth - 28, 10, 'F');
      }

      // Status color
      if (test.status === 'High') {
        doc.setTextColor(239, 68, 68);
      } else if (test.status === 'Low') {
        doc.setTextColor(245, 158, 11);
      } else {
        doc.setTextColor(16, 185, 129);
      }

      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(50, 50, 50);
      doc.text(test.name.substring(0, 35), 16, y + 1);
      doc.text(test.value || '-', 90, y + 1);
      doc.text(test.normal_range || '-', 120, y + 1);

      // Status badge
      if (test.status === 'High') {
        doc.setTextColor(239, 68, 68);
      } else if (test.status === 'Low') {
        doc.setTextColor(245, 158, 11);
      } else {
        doc.setTextColor(16, 185, 129);
      }
      doc.setFont('helvetica', 'bold');
      doc.text(test.status || '-', 170, y + 1);
      y += 12;
    });
  }

  y += 10;

  // Summary section
  if (report.summary) {
    if (y > 220) {
      doc.addPage();
      y = 20;
    }

    // Summary box
    doc.setDrawColor(79, 142, 247);
    doc.setLineWidth(0.3);
    doc.setFillColor(240, 244, 255);
    doc.roundedRect(14, y, pageWidth - 28, 8, 2, 2, 'FD');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(79, 142, 247);
    doc.text('AI Summary', 18, y + 5.5);
    y += 14;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    const splitSummary = doc.splitTextToSize(report.summary, pageWidth - 30);
    doc.text(splitSummary, 14, y);
    y += splitSummary.length * 5 + 10;
  }

  // Disclaimer
  if (y > 250) {
    doc.addPage();
    y = 20;
  }
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'italic');
  const disclaimer = 'Disclaimer: This report is generated by AI and is for informational purposes only. Always consult a qualified healthcare professional for medical advice.';
  const splitDisclaimer = doc.splitTextToSize(disclaimer, pageWidth - 28);
  doc.text(splitDisclaimer, 14, y + 10);

  // Footer
  doc.setFillColor(15, 15, 24);
  doc.rect(0, 282, pageWidth, 15, 'F');
  doc.setFontSize(8);
  doc.setTextColor(79, 142, 247);
  doc.setFont('helvetica', 'bold');
  doc.text('MediScan AI', 14, 290);
  doc.setTextColor(120, 120, 120);
  doc.setFont('helvetica', 'normal');
  doc.text('Powered by Advanced AI', 14, 294);
  doc.text(`Page 1`, pageWidth - 14, 290, { align: 'right' });

  // Save
  doc.save(`MediScan_Report_${userName}_${new Date().toLocaleDateString().replace(/\//g, '-')}.pdf`);
};